modLoader="javafml" #mandatory
loaderVersion="[36.2.0,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/kmfisk/ZAWAEssentials/issues" #optional

[[mods]] #mandatory
    modId="zawaessentials" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="ZAWA: Essentials Addon" #mandatory
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    logoFile="logo.png" #optional
    credits="fisk - Models, textures, animations; Mnesikos - Code, base code, moral support, cat herding; Lysaell - Data book entries, editing; Keaka; Platinum_2; Chinchillin; Shoresey; JamieWynn; " #optional
    authors="fisk, Mnesikos" #optional
    description='''
Official ZAWA addon by fisk and Mnesikos. For all the animals not cool enough
for the real roster spots.

An add-on pack for ZAWA: Evolved 1.16.5.
'''

[[dependencies.zawaessentials]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.2.20,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.zawaessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zawaessentials]]
    modId="zawa"
    mandatory=true
    versionRange="[1.16.5-1.0.2-BeefBeta-TropicalExpedition3,)"
    ordering="AFTER"
    side="BOTH"
